import PDFDocument from 'pdfkit'
import fs from 'fs'
import path from 'path'

export interface ReportData {
  id: string
  query: string
  output: string
  confidenceScore: number
  reliabilityScore: number
  trustDeviation: number
  calibrationIndex: number
  calibrationLevel: string
  riskLevel: string
  verificationLatency: number
  createdAt: Date
  claims: Array<{
    text: string
    confidence: number
    reliability: number
    verified: boolean
  }>
}

export async function generatePDFReport(data: ReportData): Promise<string> {
  return new Promise((resolve, reject) => {
    try {
      // Create reports directory if it doesn't exist
      const reportsDir = path.join(process.cwd(), 'public', 'reports')
      if (!fs.existsSync(reportsDir)) {
        fs.mkdirSync(reportsDir, { recursive: true })
      }
      
      const filename = `report-${data.id}.pdf`
      const filepath = path.join(reportsDir, filename)
      
      // Create PDF document
      const doc = new PDFDocument({ margin: 50 })
      const stream = fs.createWriteStream(filepath)
      
      doc.pipe(stream)
      
      // Header
      doc.fontSize(24)
         .fillColor('#1e40af')
         .text('Trust Calibration Report', { align: 'center' })
         .moveDown()
      
      // Metadata
      doc.fontSize(10)
         .fillColor('#666')
         .text(`Report ID: ${data.id}`, { align: 'right' })
         .text(`Generated: ${new Date().toLocaleString()}`, { align: 'right' })
         .moveDown(2)
      
      // Query Section
      doc.fontSize(16)
         .fillColor('#000')
         .text('Query', { underline: true })
         .moveDown(0.5)
      
      doc.fontSize(12)
         .fillColor('#333')
         .text(data.query)
         .moveDown(1.5)
      
      // Metrics Section
      doc.fontSize(16)
         .fillColor('#000')
         .text('Trust Metrics', { underline: true })
         .moveDown(0.5)
      
      const metrics = [
        { label: 'Confidence Score', value: `${data.confidenceScore.toFixed(1)}%` },
        { label: 'Reliability Score', value: `${data.reliabilityScore.toFixed(1)}%` },
        { label: 'Trust Deviation', value: `${data.trustDeviation.toFixed(1)}%` },
        { label: 'Calibration Index', value: `${data.calibrationIndex.toFixed(1)}` },
        { label: 'Calibration Level', value: data.calibrationLevel.toUpperCase() },
        { label: 'Risk Level', value: data.riskLevel.toUpperCase() },
        { label: 'Verification Latency', value: `${data.verificationLatency}ms` },
      ]
      
      doc.fontSize(11)
      metrics.forEach(metric => {
        doc.fillColor('#000')
           .text(`${metric.label}: `, { continued: true })
           .fillColor('#1e40af')
           .text(metric.value)
      })
      
      doc.moveDown(1.5)
      
      // Model Output Section
      doc.fontSize(16)
         .fillColor('#000')
         .text('Model Output', { underline: true })
         .moveDown(0.5)
      
      doc.fontSize(11)
         .fillColor('#333')
         .text(data.output, { align: 'justify' })
         .moveDown(1.5)
      
      // Claims Section
      doc.fontSize(16)
         .fillColor('#000')
         .text('Verified Claims', { underline: true })
         .moveDown(0.5)
      
      data.claims.forEach((claim, index) => {
        const statusColor = claim.verified ? '#10b981' : '#ef4444'
        const statusText = claim.verified ? '✓ VERIFIED' : '✗ UNVERIFIED'
        
        doc.fontSize(10)
           .fillColor('#000')
           .text(`${index + 1}. ${claim.text}`)
        
        doc.fontSize(9)
           .fillColor('#666')
           .text(`   Confidence: ${claim.confidence.toFixed(1)}% | Reliability: ${claim.reliability.toFixed(1)}%`, {
             continued: true
           })
           .fillColor(statusColor)
           .text(` | ${statusText}`)
           .moveDown(0.5)
      })
      
      // Footer
      doc.fontSize(8)
         .fillColor('#999')
         .text(
           'This report was generated by Trust Calibration Layer - AI Trust Intelligence Platform',
           50,
           doc.page.height - 50,
           { align: 'center' }
         )
      
      // Finalize PDF
      doc.end()
      
      stream.on('finish', () => {
        resolve(`/reports/${filename}`)
      })
      
      stream.on('error', reject)
      
    } catch (error) {
      reject(error)
    }
  })
}
